### ISSUE TITLE
5 steps status

### ISSUE THREAD

**Issue by PirateCode-eth** [ForeverPFP/frontend#18]
Actually the 5 steps can be jump directly to step 3 if someone has primary ENS already.

So, we need to detect status and decide which step the user will going to after connecting user's wallet? @0xtiby

**Comment by 0xtiby** [comment]
Sure, 
User connect wallet we check for ens name. so step 1 and 2 doesn't appear. 
I'm not sure to understand what the purpose of 4, 
And for 5 we add the possibility to set the record directly in the app ?  Let people link their twitter account right ?

**Comment by PirateCode-eth** [comment]
step 1 & 2 can be confirm by the user, if they want to set primary PFP to this ENS, need to be showed I think.

the purpose of 4 is that let the primary PFP user find the twitter accounts with the same primary PFP collection set.

once the primary PFP is set, we have the collection address of the PFP, then `getPrimaryPFPCommunityENS(address collectionAddress)` and `getTwitterAccountsByENS(address[] addresses)`.

**Comment by PirateCode-eth** [comment]
> Sure, User connect wallet we check for ens name. so step 1 and 2 doesn't appear. I'm not sure to understand what the purpose of 4, And for 5 we add the possibility to set the record directly in the app ? Let people link their twitter account right ?

yes, step 5 can be done by the product link to twitter.

**Comment by 0xtiby** [comment]
@PirateCode-eth  What do you think of this. Where each is collapsible with the action to do inside. 
![Sizzy-MacBook Air localhost 16May 07 07](https://github.com/ForeverPFP/frontend/assets/101003754/f6dd62dd-119d-4a17-a5ea-0b1f4c9c5b08)

**Comment by PirateCode-eth** [comment]
Looks cool.

**Comment by 0xtiby** [comment]
@PirateCode-eth  Preview : 
![image](https://github.com/ForeverPFP/frontend/assets/101003754/a32912b9-63d8-4d1b-b1f2-422aa5ef963b)

**Comment by PirateCode-eth** [comment]
it's cool. LFG.

**Comment by PirateCode-eth** [comment]
Oh, @0xtiby there is one situation that we need to considering about. most of PFP players use cold wallet which is a vault to save PFP, and use hotwallet with ENS to do suffering in web3. delegate.cash is a good tool for that, that's what setPrimaryForDelegate function designed for primary PFP.

maybe you can think about how to make people easier to use delegate function to set primary PFP?

**Comment by 0xtiby** [comment]
Yes I will add it

**Comment by 0xtiby** [comment]
@PirateCode-eth Maybe the step 4 can be remove until we build the social website etc...

**Comment by PirateCode-eth** [comment]
step 4 can be done by onchain data, but need subgraph support, we talked about it before:
1. after primary PFP contract, we have [this](https://github.com/ForeverPFP/primary-pfp-contract/blob/main/src/IPrimaryPFP.sol#L74) function to get user's PFP collection address, 
2. use subgraph to archive `address[] getCommunityPrimaryAddresses(address collectionContract_) ` to get all the users who set primary PFP
3. get their primary ENS content of twitter link, then we can make people find community onchain.

**Comment by 0xtiby** [comment]
Because we can't mark as check the step 4 and to have better consistency with checked step I move the step 4 as 5. 
@PirateCode-eth

**Comment by PirateCode-eth** [comment]
Yes, you are right :)
